[package]
name = "cubiedays/girraframework"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
include = ["lib", "default.project.json", "LICENSE"]
realm = "shared"
description = "Girra's dream framework is based on success, comfort, and an easy guide."
license = "MIT"

[dependencies]
Network = "imezx/fastnet2@0.9.6"
Promise = "red-blox/promise@1.1.1"
Signal = "stravant/goodsignal@0.2.1"