[package]
name = "cubiedays/girra-framework"
version = "1.5.4"
description = "Girra's dream framework is based on success, comfort, and an easy guide."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

license = "MIT"
include = [
    "default.project.json", 
    "lib", 
    "lib/**", 
    "LICENSE", 
    "wally.toml"
]

exclude = ["**"]

[dependencies]
Promise = "red-blox/promise@1.1.1"
Signal = "stravant/goodsignal@0.2.1"

